language: node_js
os:
  - linux
compiler: clang
node_js:
  - "4.2"
matrix:
  allow_failures:
before_install:
  - npm install node-gyp -g
install:
  - npm install
before_script:
script:
  - npm test
deploy:
  provider: npm
  email: devraindance@gmail.com
  api_key:
    secure: Z/hpH3P793Abzp9XQGzToXjnG379wKdNbFg1vPIlRHgOUDVILLp+J7aRNCA3RihnahS3EBvlhXc1Rpc+iAW0Dbc6E2g2w5OOAOrgYMIVOf3IrJ9qn3wXD35QUI/pTzHmliExAmvdeHJovf8PlkI7tzgVojfoqCdRs7uiJG6MBUM=
  on:
    branch: master
    repo: eljefederodeodeljefe/node-cpython
