
environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "0.11"
    - nodejs_version: "1.8.1"
    - nodejs_version: "2.0.2"

matrix:
  allow_failures:
    - nodejs_version: "0.11"
    - nodejs_version: "2.0.2"

platform:
  - x86
  - x64

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install gulpjs/gulp-cli#4.0 -g
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
